name: DevOps Local Ansible CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint
          ansible-galaxy collection install community.docker

      - name: Lint
        run: |
          ansible-lint ansible/site.yml
          yamllint .

      - name: Syntax check
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/site.yml --syntax-check

  cd_local:
    runs-on: self-hosted
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Install collection
        run: |
          ansible-galaxy collection install community.docker

      - name: Deploy (local machine)
        run: |
          cd ansible
          ansible-playbook -i inventory.ini site.yml
